name: build_Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: '1.0_7'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap Procursus
        uses: w2599/procursus-action@main
        with:
          packages: ldid trustcache
          cache: true
          cache-path: ~/__cache
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos

      - name: Pre env
        run: |
         sT=$(TZ=UTC-8 date +'%S')
         echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
         echo "shT=$(TZ=UTC-8 date +'%Y.%m.%d/%H.%M').${sT}" >> $GITHUB_ENV
         echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Log env
        run: |
         echo ${{ env.VERSION }}
         echo ${{ env.msT }}
         echo ${{ env.shT }}
         echo ${{ env.logT }}

      - name: Pre code
        run: |
          sed -i '' "s/AAA/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAB/友情提示:Fugumax转用此版本会重建/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAC/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/CCC/${{ secrets.DOPAMINE_TOKEN }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/CCC/${{ secrets.DOPAMINE_TOKEN }}/g" ./Dopamine/Dopamine/UI/Views/UpdateDownloadingView.swift
          sed -i '' "s/"opa334"/"w2599"/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/"opa334"/"w2599"/g" ./Dopamine/Dopamine/UI/Views/UpdateDownloadingView.swift

      - name: Pre body
        run: |
          echo -e "版本  ${{ env.VERSION }}\n编译时间戳  ${{ env.msT }}\n北京时间  ${{ env.shT }}" >> body.txt
          echo -e "\n\n增删改:" >> body.txt
          echo -e "\n${{ env.logT }}" >> body.txt
          echo -e "继续同步代码" >> body.txt
          echo -e "2023年4月28日 10:25:30" >> body.txt
          echo -e "1.0_7" >> body.txt
          echo -e "跟随官方代码变动重写挂载" >> body.txt
          echo -e "2023年4月23日 15:22:09" >> body.txt
          echo -e "1.0_6" >> body.txt
          echo -e "魔改应用内更新" >> body.txt
          echo -e "热挂载目录(越狱后设置界面)" >> body.txt
          echo -e "默认不注入/Dev" >> body.txt
          echo -e "自动关闭wifi等待时间1秒变3秒" >> body.txt
          echo -e "自动重启用户空间改为按钮" >> body.txt

      - name: Pre keychain
        run: |
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A

      - name: Build tipa
        run: |
          export THEOS=$HOME/theos
          make
          cp Dopamine/Dopamine.tipa Dopamine.tipa
          mv Dopamine/Dopamine.tipa Dopamine_${{ env.msT }}.tipa

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: main
          body_path: body.txt
       #   token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.tipa
